"""Deterministic, clearly synthetic demo dataset.

The dataset is generated from a fixed catalog and a seeded ``random.Random``
instance, so two runs always produce byte-identical data (this is what makes the
tests and the KPI assertions reproducible).

It is **synthetic sample data** that exists only to exercise the pipeline. It
does not describe any real company, customer or transaction. ``revenue`` is
always computed as ``quantity * unit_price``; it is never hand-invented.

Besides clean rows the dataset contains a set of *documented defects* so the
validation and cleaning stages have something meaningful to report.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Any

import pandas as pd

from src.data.io import frame_from_records

DEMO_SEED = 20250101

DEMO_DATA_DISCLAIMER = (
    "Synthetic sample dataset generated by the application for demonstration "
    "and testing. Not real company data."
)

# Header spellings deliberately use common aliases ("Order Date", "Qty",
# "Unit Price", ...) so the header-normalisation rules are exercised.
RAW_HEADERS: tuple[str, ...] = (
    "Order Date",
    "Order ID",
    "Customer",
    "Product",
    "Category",
    "Qty",
    "Unit Price",
    "Revenue",
    "Region",
    "Order Status",
    "Feedback",
)

CATALOG: tuple[tuple[str, str, float], ...] = (
    ("Wireless Mouse", "Electronics", 24.90),
    ("Mechanical Keyboard", "Electronics", 89.00),
    ("Noise Cancelling Headphones", "Electronics", 129.50),
    ("Espresso Machine", "Home & Kitchen", 210.00),
    ("Ceramic Cookware Set", "Home & Kitchen", 145.75),
    ("Desk Lamp", "Office Supplies", 32.40),
    ("Ergonomic Office Chair", "Office Supplies", 189.99),
    ("A4 Notebook Pack", "Office Supplies", 12.60),
    ("Camping Tent 4P", "Outdoors", 249.00),
    ("Insulated Water Bottle", "Outdoors", 21.75),
    ("Trail Running Shoes", "Outdoors", 118.30),
    ("Cotton T-Shirt", "Apparel", 19.99),
    ("Fleece Jacket", "Apparel", 74.50),
)

CUSTOMERS: tuple[str, ...] = (
    "Acme Retail",
    "Blue Ridge Traders",
    "Cedar & Co",
    "Delta Wholesale",
    "Evergreen Supplies",
    "Fairview Stores",
    "Granite Partners",
    "Harbor Point LLC",
)

REGIONS: tuple[str, ...] = ("North", "South", "East", "West")

# (status, weight) - deterministic weighting per row via random.choices(seed).
STATUS_WEIGHTS: tuple[tuple[str, int], ...] = (
    ("Completed", 82),
    ("Pending", 10),
    ("Cancelled", 5),
    ("Refunded", 3),
)

# Monthly catalog emphasis: February deliberately shifts demand away from
# Outdoors towards Office Supplies so period-over-period analytics have
# something real to compare. This is a synthetic pattern, not a claim about a
# market.
MONTH_PLAN: tuple[tuple[int, int, int, dict[str, float]], ...] = (
    # year, month, orders, category emphasis
    (2025, 1, 22, {"Electronics": 1.0, "Home & Kitchen": 1.0, "Office Supplies": 1.0,
                   "Outdoors": 1.4, "Apparel": 1.0}),
    (2025, 2, 20, {"Electronics": 1.1, "Home & Kitchen": 1.0, "Office Supplies": 1.5,
                   "Outdoors": 0.6, "Apparel": 1.2}),
)

FEEDBACK_POOL: tuple[str, ...] = (
    "Delivery arrived a day late but the product is excellent.",
    "Great quality, will order again.",
    "The packaging was damaged on arrival.",
    "Exactly as described, fast shipping.",
    "Support took three days to answer my question.",
    "Item stopped working after two weeks.",
    "Good value for the price.",
    "Wrong colour was shipped, still waiting for a replacement.",
    "Instructions were unclear but the product works well.",
    "Perfect for our office, ordering more next month.",
)


def _pick_product(rng: random.Random, emphasis: dict[str, float]) -> tuple[str, str, float]:
    items = list(CATALOG)
    weights = [emphasis.get(category, 1.0) for _, category, _ in items]
    return rng.choices(items, weights=weights, k=1)[0]


def _base_rows() -> list[dict[str, Any]]:
    """Generate the clean part of the dataset (fully deterministic)."""
    rng = random.Random(DEMO_SEED)
    statuses = [status for status, _ in STATUS_WEIGHTS]
    status_weights = [weight for _, weight in STATUS_WEIGHTS]

    rows: list[dict[str, Any]] = []
    counter = 1
    for year, month, order_count, emphasis in MONTH_PLAN:
        for day in range(1, order_count + 1):
            product, category, price = _pick_product(rng, emphasis)
            quantity = rng.randint(10, 18) if rng.random() < 0.12 else rng.randint(1, 9)
            status = rng.choices(statuses, weights=status_weights, k=1)[0]
            feedback = (
                FEEDBACK_POOL[rng.randrange(len(FEEDBACK_POOL))] if rng.random() < 0.35 else ""
            )
            rows.append(
                {
                    "Order Date": f"{year}-{month:02d}-{min(day, 28):02d}",
                    "Order ID": f"SO-{year}-{counter:04d}",
                    "Customer": CUSTOMERS[rng.randrange(len(CUSTOMERS))],
                    "Product": product,
                    "Category": category,
                    "Qty": quantity,
                    "Unit Price": price,
                    # Revenue is derived, never invented:
                    "Revenue": round(quantity * price, 2),
                    "Region": REGIONS[rng.randrange(len(REGIONS))],
                    "Order Status": status,
                    "Feedback": feedback,
                }
            )
            counter += 1
    return rows


def _defect_rows(clean_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Documented defects, one per validation/cleaning rule under test.

    Each defect is deliberate: removing one would remove test coverage for the
    rule named in its comment.
    """
    def clone(position: int) -> dict[str, Any]:
        return dict(clean_rows[position])

    defects: list[dict[str, Any]] = []

    # 1. Exact duplicate of an existing order -> duplicate removal.
    defects.append(clone(0))

    # 2. Same order id with conflicting quantity -> first occurrence wins.
    conflicting = clone(3)
    conflicting["Qty"] = 99
    defects.append(conflicting)

    # 3. Whitespace noise + category/region/status aliases + mixed case.
    noisy = clone(5)
    noisy["Order ID"] = "  SO-2025-9001  "
    noisy["Product"] = "  Desk Lamp  "
    noisy["Category"] = " home and kitchen "
    noisy["Region"] = " north "
    noisy["Order Status"] = "completed"
    defects.append(noisy)

    # 4. Currency formatted price -> numeric conversion rule.
    currency = clone(6)
    currency["Order ID"] = "SO-2025-9002"
    currency["Qty"] = 2
    currency["Unit Price"] = "$1,299.00"
    currency["Revenue"] = 2598.00
    defects.append(currency)

    # 5. Revenue that does not match quantity * unit_price -> recalculated.
    mismatch = clone(7)
    mismatch["Order ID"] = "SO-2025-9003"
    mismatch["Qty"] = 5
    mismatch["Unit Price"] = 40.0
    mismatch["Revenue"] = 100.0
    defects.append(mismatch)

    # 6. Impossible (and ambiguous) date -> record rejected.
    bad_date = clone(8)
    bad_date["Order ID"] = "SO-2025-9004"
    bad_date["Order Date"] = "31/02/2025"
    defects.append(bad_date)

    # 7. Missing date -> record rejected.
    missing_date = clone(9)
    missing_date["Order ID"] = "SO-2025-9005"
    missing_date["Order Date"] = ""
    defects.append(missing_date)

    # 8. Quantity below the documented minimum -> record rejected.
    zero_quantity = clone(10)
    zero_quantity["Order ID"] = "SO-2025-9006"
    zero_quantity["Qty"] = 0
    defects.append(zero_quantity)

    # 9. Missing quantity marker "N/A" -> missing value, record rejected.
    missing_quantity = clone(11)
    missing_quantity["Order ID"] = "SO-2025-9007"
    missing_quantity["Qty"] = "N/A"
    defects.append(missing_quantity)

    # 10. Non numeric unit price -> record rejected.
    bad_price = clone(12)
    bad_price["Order ID"] = "SO-2025-9008"
    bad_price["Unit Price"] = "abc"
    defects.append(bad_price)

    # 11. Missing product name -> record rejected.
    missing_product = clone(13)
    missing_product["Order ID"] = "SO-2025-9009"
    missing_product["Product"] = ""
    defects.append(missing_product)

    # 12. Missing customer -> replaced by the documented default value.
    missing_customer = clone(14)
    missing_customer["Order ID"] = "SO-2025-9010"
    missing_customer["Customer"] = ""
    defects.append(missing_customer)

    # 13. Unknown region -> record rejected (categorical whitelist).
    unknown_region = clone(15)
    unknown_region["Order ID"] = "SO-2025-9011"
    unknown_region["Region"] = "Central"
    defects.append(unknown_region)

    # 14. Unknown status -> record rejected (categorical whitelist).
    unknown_status = clone(16)
    unknown_status["Order ID"] = "SO-2025-9012"
    unknown_status["Order Status"] = "Archived"
    defects.append(unknown_status)

    # 15. Revenue far above the configured outlier threshold -> warning only.
    outlier = clone(17)
    outlier["Order ID"] = "SO-2025-9013"
    outlier["Qty"] = 200
    outlier["Unit Price"] = 300.0
    outlier["Revenue"] = 60000.00
    defects.append(outlier)

    # 16. Completely blank row -> dropped while preparing the dataset.
    defects.append(dict.fromkeys(RAW_HEADERS, ""))

    return defects


@dataclass(frozen=True)
class DemoDataset:
    """Immutable, deterministic synthetic dataset."""

    rows: tuple[dict[str, Any], ...]

    @property
    def headers(self) -> tuple[str, ...]:
        return RAW_HEADERS

    @property
    def row_count(self) -> int:
        return len(self.rows)

    def to_frame(self) -> pd.DataFrame:
        """Raw frame using the spreadsheet-row index convention."""
        return frame_from_records(list(self.rows))

    def to_values(self) -> list[list[Any]]:
        """Google Sheets style value grid (header row + data rows)."""
        grid: list[list[Any]] = [list(RAW_HEADERS)]
        grid.extend([[row.get(header, "") for header in RAW_HEADERS] for row in self.rows])
        return grid

    def to_csv_text(self) -> str:
        """CSV export, used by ``python main.py demo-data --out <path>``."""
        rows = [list(RAW_HEADERS)]
        rows.extend([[row.get(header, "") for header in RAW_HEADERS] for row in self.rows])
        return "\n".join(",".join(_csv_cell(cell) for cell in row) for row in rows) + "\n"


def _csv_cell(value: Any) -> str:
    text = "" if value is None else str(value)
    if any(character in text for character in (",", '"', "\n")):
        return '"' + text.replace('"', '""') + '"'
    return text


def build_demo_dataset() -> DemoDataset:
    """Build the synthetic dataset (clean rows + documented defects)."""
    clean_rows = _base_rows()
    return DemoDataset(rows=tuple(clean_rows + _defect_rows(clean_rows)))
